// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is the container type for the response payload of the
    /// &lt;b&gt;getItemAspectsForCategory&lt;/b&gt; call.
    /// </summary>
    public partial class AspectMetadata
    {
        /// <summary>
        /// Initializes a new instance of the AspectMetadata class.
        /// </summary>
        public AspectMetadata() { }

        /// <summary>
        /// Initializes a new instance of the AspectMetadata class.
        /// </summary>
        public AspectMetadata(IList<Aspect> aspects = default(IList<Aspect>))
        {
            Aspects = aspects;
        }

        /// <summary>
        /// A list of item aspects (for example, color) that are appropriate
        /// or necessary for accurately describing items in a particular leaf
        /// category. Each category has a different set of aspects and
        /// different requirements for aspect values. Sellers are required or
        /// encouraged to provide one or more acceptable values for each
        /// aspect when offering an item in that category on eBay.
        /// </summary>
        [JsonProperty(PropertyName = "aspects")]
        public IList<Aspect> Aspects { get; set; }

    }
}
