// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type contains identifying information for the category tree
    /// associated with a particular eBay marketplace.
    /// </summary>
    public partial class BaseCategoryTree
    {
        /// <summary>
        /// Initializes a new instance of the BaseCategoryTree class.
        /// </summary>
        public BaseCategoryTree() { }

        /// <summary>
        /// Initializes a new instance of the BaseCategoryTree class.
        /// </summary>
        public BaseCategoryTree(string categoryTreeId = default(string), string categoryTreeVersion = default(string))
        {
            CategoryTreeId = categoryTreeId;
            CategoryTreeVersion = categoryTreeVersion;
        }

        /// <summary>
        /// The unique identifier of the eBay category tree for the specified
        /// marketplace.
        /// </summary>
        [JsonProperty(PropertyName = "categoryTreeId")]
        public string CategoryTreeId { get; set; }

        /// <summary>
        /// The version of the category tree identified by categoryTreeId.
        /// It's a good idea to cache this value for comparison so you can
        /// determine if this category tree has been modified in subsequent
        /// calls.
        /// </summary>
        [JsonProperty(PropertyName = "categoryTreeVersion")]
        public string CategoryTreeVersion { get; set; }

    }
}
