// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type contains information about a suggested category tree leaf
    /// node that corresponds to keywords provided in the request. It
    /// includes details about each of the category's ancestor nodes
    /// extending up to the root of the category tree.
    /// </summary>
    public partial class CategorySuggestion
    {
        /// <summary>
        /// Initializes a new instance of the CategorySuggestion class.
        /// </summary>
        public CategorySuggestion() { }

        /// <summary>
        /// Initializes a new instance of the CategorySuggestion class.
        /// </summary>
        public CategorySuggestion(Category category = default(Category), IList<AncestorReference> categoryTreeNodeAncestors = default(IList<AncestorReference>), int? categoryTreeNodeLevel = default(int?), string relevancy = default(string))
        {
            Category = category;
            CategoryTreeNodeAncestors = categoryTreeNodeAncestors;
            CategoryTreeNodeLevel = categoryTreeNodeLevel;
            Relevancy = relevancy;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "category")]
        public Category Category { get; set; }

        /// <summary>
        /// An ordered list of category references that describes the location
        /// of the suggested category in the specified category tree. The
        /// list identifies the category's ancestry as a sequence of parent
        /// nodes, from the current node's immediate parent to the root node
        /// of the category tree. Note: The root node of a full default
        /// category tree includes categoryId and categoryName fields, but
        /// their values should not be relied upon. They provide no useful
        /// information for application development.
        /// </summary>
        [JsonProperty(PropertyName = "categoryTreeNodeAncestors")]
        public IList<AncestorReference> CategoryTreeNodeAncestors { get; set; }

        /// <summary>
        /// The absolute level of the category tree node in the hierarchy of
        /// its category tree. Note: The root node of any full category tree
        /// is always at level 0.
        /// </summary>
        [JsonProperty(PropertyName = "categoryTreeNodeLevel")]
        public int? CategoryTreeNodeLevel { get; set; }

        /// <summary>
        /// This field is reserved for internal or future use.
        /// </summary>
        [JsonProperty(PropertyName = "relevancy")]
        public string Relevancy { get; set; }

    }
}
