// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to express a dollar value and the applicable
    /// currency.
    /// </summary>
    public partial class Amount
    {
        /// <summary>
        /// Initializes a new instance of the Amount class.
        /// </summary>
        public Amount() { }

        /// <summary>
        /// Initializes a new instance of the Amount class.
        /// </summary>
        public Amount(string currency = default(string), string value = default(string))
        {
            Currency = currency;
            Value = value;
        }

        /// <summary>
        /// A three-digit string value respresenting the type of currency
        /// being used. Both the value and currency fields are
        /// required/always returned when expressing prices. See the
        /// CurrencyCodeEnum type for the full list of currencies and their
        /// corresponding three-digit string values.
        /// </summary>
        [JsonProperty(PropertyName = "currency")]
        public string Currency { get; set; }

        /// <summary>
        /// A string representation of a dollar value expressed in the
        /// currency specified in the currency field. Both the value and
        /// currency fields are required/always returned when expressing
        /// prices.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
