// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to specify the quantity of the inventory item that
    /// is available for purchase if the item will be shipped to the buyer,
    /// and the quantity of the inventory item that is available for In-Store
    /// Pickup at one or more of the merchant's physical stores. In-Store
    /// Pickup is only available to large merchants selling on the US, UK,
    /// Germany, and Australia sites.
    /// </summary>
    public partial class Availability
    {
        /// <summary>
        /// Initializes a new instance of the Availability class.
        /// </summary>
        public Availability() { }

        /// <summary>
        /// Initializes a new instance of the Availability class.
        /// </summary>
        public Availability(IList<PickupAtLocationAvailability> pickupAtLocationAvailability = default(IList<PickupAtLocationAvailability>), ShipToLocationAvailability shipToLocationAvailability = default(ShipToLocationAvailability))
        {
            PickupAtLocationAvailability = pickupAtLocationAvailability;
            ShipToLocationAvailability = shipToLocationAvailability;
        }

        /// <summary>
        /// This container consists of an array of one or more of the
        /// merchant's physical store locations where the inventory item is
        /// available for In-Store Pickup orders. The merchant's location,
        /// the quantity available, and the fulfillment time (how soon the
        /// item will be ready for pickup after the order takes place) are
        /// all in this container. In-Store Pickup is only available to large
        /// merchants selling on the US, UK, Germany, and Australia sites.
        /// </summary>
        [JsonProperty(PropertyName = "pickupAtLocationAvailability")]
        public IList<PickupAtLocationAvailability> PickupAtLocationAvailability { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shipToLocationAvailability")]
        public ShipToLocationAvailability ShipToLocationAvailability { get; set; }

    }
}
