// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This is the base response of the
    /// &lt;strong&gt;createOrReplaceInventoryItem&lt;/strong&gt;,
    /// &lt;strong&gt;createOrReplaceInventoryItemGroup&lt;/strong&gt;,  and
    /// &lt;strong&gt;createOrReplaceProductCompatibility&lt;/strong&gt;
    /// calls. A response payload will only be returned for these three
    /// calls if one or more errors or warnings occur with the call.
    /// </summary>
    public partial class BaseResponse
    {
        /// <summary>
        /// Initializes a new instance of the BaseResponse class.
        /// </summary>
        public BaseResponse() { }

        /// <summary>
        /// Initializes a new instance of the BaseResponse class.
        /// </summary>
        public BaseResponse(IList<Error> warnings = default(IList<Error>))
        {
            Warnings = warnings;
        }

        /// <summary>
        /// This container will be returned in a call response payload if one
        /// or more warnings or errors are triggered when an Inventory API
        /// call is made. This container will contain detailed information
        /// about the error or warning.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
