// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the &lt;strong&gt;bestOfferTerms&lt;/strong&gt;
    /// container, which is used if the seller would like to support the Best
    /// Offer feature on their listing.
    /// </summary>
    public partial class BestOffer
    {
        /// <summary>
        /// Initializes a new instance of the BestOffer class.
        /// </summary>
        public BestOffer() { }

        /// <summary>
        /// Initializes a new instance of the BestOffer class.
        /// </summary>
        public BestOffer(Amount autoAcceptPrice = default(Amount), Amount autoDeclinePrice = default(Amount), bool? bestOfferEnabled = default(bool?))
        {
            AutoAcceptPrice = autoAcceptPrice;
            AutoDeclinePrice = autoDeclinePrice;
            BestOfferEnabled = bestOfferEnabled;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "autoAcceptPrice")]
        public Amount AutoAcceptPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "autoDeclinePrice")]
        public Amount AutoDeclinePrice { get; set; }

        /// <summary>
        /// This field indicates whether or not the Best Offer feature is
        /// enabled for the listing. A seller can enable the Best Offer
        /// feature for a listing as long as the category supports the Best
        /// Offer feature. The seller includes this field and sets its value
        /// to true to enable Best Offer feature.
        /// </summary>
        [JsonProperty(PropertyName = "bestOfferEnabled")]
        public bool? BestOfferEnabled { get; set; }

    }
}
