// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base response of the
    /// &lt;strong&gt;bulkGetInventoryItem&lt;/strong&gt; method.
    /// </summary>
    public partial class BulkGetInventoryItemResponse
    {
        /// <summary>
        /// Initializes a new instance of the BulkGetInventoryItemResponse
        /// class.
        /// </summary>
        public BulkGetInventoryItemResponse() { }

        /// <summary>
        /// Initializes a new instance of the BulkGetInventoryItemResponse
        /// class.
        /// </summary>
        public BulkGetInventoryItemResponse(IList<GetInventoryItemResponse> responses = default(IList<GetInventoryItemResponse>))
        {
            Responses = responses;
        }

        /// <summary>
        /// This is the base container of the bulkGetInventoryItem response.
        /// The results of each attempted inventory item retrieval is
        /// captured under this container.
        /// </summary>
        [JsonProperty(PropertyName = "responses")]
        public IList<GetInventoryItemResponse> Responses { get; set; }

    }
}
