// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the response payload of the
    /// &lt;strong&gt;bulkMigrateListings&lt;/strong&gt; call.
    /// </summary>
    public partial class BulkMigrateListingResponse
    {
        /// <summary>
        /// Initializes a new instance of the BulkMigrateListingResponse class.
        /// </summary>
        public BulkMigrateListingResponse() { }

        /// <summary>
        /// Initializes a new instance of the BulkMigrateListingResponse class.
        /// </summary>
        public BulkMigrateListingResponse(IList<MigrateListingResponse> responses = default(IList<MigrateListingResponse>))
        {
            Responses = responses;
        }

        /// <summary>
        /// This is the base container of the response payload of the
        /// bulkMigrateListings call. The results of each attempted listing
        /// migration is captured under this container.
        /// </summary>
        [JsonProperty(PropertyName = "responses")]
        public IList<MigrateListingResponse> Responses { get; set; }

    }
}
