// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the base response of the
    /// &lt;strong&gt;bulkPublishOffer&lt;/strong&gt; method.
    /// </summary>
    public partial class BulkPublishResponse
    {
        /// <summary>
        /// Initializes a new instance of the BulkPublishResponse class.
        /// </summary>
        public BulkPublishResponse() { }

        /// <summary>
        /// Initializes a new instance of the BulkPublishResponse class.
        /// </summary>
        public BulkPublishResponse(IList<OfferResponseWithListingId> responses = default(IList<OfferResponseWithListingId>))
        {
            Responses = responses;
        }

        /// <summary>
        /// A node is returned under the responses container to indicate the
        /// success or failure of each offer that the seller was attempting
        /// to publish.
        /// </summary>
        [JsonProperty(PropertyName = "responses")]
        public IList<OfferResponseWithListingId> Responses { get; set; }

    }
}
