// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base request of the
    /// &lt;strong&gt;bulkCreateOffer&lt;/strong&gt; method, which is used to
    /// create up to 25 new offers.
    /// </summary>
    public partial class BulkEbayOfferDetailsWithKeys
    {
        /// <summary>
        /// Initializes a new instance of the BulkEbayOfferDetailsWithKeys
        /// class.
        /// </summary>
        public BulkEbayOfferDetailsWithKeys() { }

        /// <summary>
        /// Initializes a new instance of the BulkEbayOfferDetailsWithKeys
        /// class.
        /// </summary>
        public BulkEbayOfferDetailsWithKeys(IList<EbayOfferDetailsWithKeys> requests = default(IList<EbayOfferDetailsWithKeys>))
        {
            Requests = requests;
        }

        /// <summary>
        /// The details of each offer that is being created is passed in under
        /// this container. Up to 25 offers can be created with one
        /// bulkCreateOffer call.
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<EbayOfferDetailsWithKeys> Requests { get; set; }

    }
}
