// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the base request of the
    /// &lt;strong&gt;bulkGetInventoryItem&lt;/strong&gt; method.
    /// </summary>
    public partial class BulkGetInventoryItem
    {
        /// <summary>
        /// Initializes a new instance of the BulkGetInventoryItem class.
        /// </summary>
        public BulkGetInventoryItem() { }

        /// <summary>
        /// Initializes a new instance of the BulkGetInventoryItem class.
        /// </summary>
        public BulkGetInventoryItem(IList<GetInventoryItem> requests = default(IList<GetInventoryItem>))
        {
            Requests = requests;
        }

        /// <summary>
        /// The seller passes in multiple SKU values under this container to
        /// retrieve multiple inventory item records. Up to 25 inventory item
        /// records can be retrieved at one time.
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<GetInventoryItem> Requests { get; set; }

    }
}
