// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the base response of the
    /// &lt;strong&gt;bulkCreateOrReplaceInventoryItem&lt;/strong&gt; method.
    /// </summary>
    public partial class BulkInventoryItemResponse
    {
        /// <summary>
        /// Initializes a new instance of the BulkInventoryItemResponse class.
        /// </summary>
        public BulkInventoryItemResponse() { }

        /// <summary>
        /// Initializes a new instance of the BulkInventoryItemResponse class.
        /// </summary>
        public BulkInventoryItemResponse(IList<InventoryItemResponse> responses = default(IList<InventoryItemResponse>))
        {
            Responses = responses;
        }

        /// <summary>
        /// This is the base container of the bulkCreateOrReplaceInventoryItem
        /// response. The results of each attempted inventory item
        /// creation/update is captured under this container.
        /// </summary>
        [JsonProperty(PropertyName = "responses")]
        public IList<InventoryItemResponse> Responses { get; set; }

    }
}
