// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base container of the
    /// &lt;strong&gt;bulkMigrateListings&lt;/strong&gt; request payload.
    /// </summary>
    public partial class BulkMigrateListing
    {
        /// <summary>
        /// Initializes a new instance of the BulkMigrateListing class.
        /// </summary>
        public BulkMigrateListing() { }

        /// <summary>
        /// Initializes a new instance of the BulkMigrateListing class.
        /// </summary>
        public BulkMigrateListing(IList<MigrateListing> requests = default(IList<MigrateListing>))
        {
            Requests = requests;
        }

        /// <summary>
        /// This is the base container of the bulkMigrateListings request
        /// payload. One to five eBay listings will be included under this
        /// container.
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<MigrateListing> Requests { get; set; }

    }
}
