// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The base request of the
    /// &lt;strong&gt;bulkCreateOrReplaceInventoryItem&lt;/strong&gt; method.
    /// </summary>
    public partial class BulkInventoryItem
    {
        /// <summary>
        /// Initializes a new instance of the BulkInventoryItem class.
        /// </summary>
        public BulkInventoryItem() { }

        /// <summary>
        /// Initializes a new instance of the BulkInventoryItem class.
        /// </summary>
        public BulkInventoryItem(IList<InventoryItemWithSkuLocale> requests = default(IList<InventoryItemWithSkuLocale>))
        {
            Requests = requests;
        }

        /// <summary>
        /// The details of each inventory item that is being created or
        /// updated is passed in under this container. Up to 25 inventory
        /// item records can be created and/or updated with one
        /// bulkCreateOrReplaceInventoryItem call.
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<InventoryItemWithSkuLocale> Requests { get; set; }

    }
}
