// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the base request of the
    /// &lt;strong&gt;bulkPublishOffer&lt;/strong&gt; method, which is used
    /// to publish up to 25 different offers.
    /// </summary>
    public partial class BulkOffer
    {
        /// <summary>
        /// Initializes a new instance of the BulkOffer class.
        /// </summary>
        public BulkOffer() { }

        /// <summary>
        /// Initializes a new instance of the BulkOffer class.
        /// </summary>
        public BulkOffer(IList<OfferKeyWithId> requests = default(IList<OfferKeyWithId>))
        {
            Requests = requests;
        }

        /// <summary>
        /// This container is used to pass in an array of offers to publish.
        /// Up to 25 offers can be published with one bulkPublishOffer method.
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<OfferKeyWithId> Requests { get; set; }

    }
}
