// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the base response of the
    /// &lt;strong&gt;bulkCreateOffer&lt;/strong&gt; method.
    /// </summary>
    public partial class BulkOfferResponse
    {
        /// <summary>
        /// Initializes a new instance of the BulkOfferResponse class.
        /// </summary>
        public BulkOfferResponse() { }

        /// <summary>
        /// Initializes a new instance of the BulkOfferResponse class.
        /// </summary>
        public BulkOfferResponse(IList<OfferSkuResponse> responses = default(IList<OfferSkuResponse>))
        {
            Responses = responses;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "responses")]
        public IList<OfferSkuResponse> Responses { get; set; }

    }
}
