// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base request payload of the
    /// &lt;strong&gt;bulkUpdatePriceQuantity&lt;/strong&gt; call. The
    /// &lt;strong&gt;bulkUpdatePriceQuantity&lt;/strong&gt; call allows the
    /// seller to update the total 'ship-to-home' quantity of one or more
    /// inventory items (up to 25) and/or to update the price and/or quantity
    /// of one or more specific published offers.
    /// </summary>
    public partial class BulkPriceQuantity
    {
        /// <summary>
        /// Initializes a new instance of the BulkPriceQuantity class.
        /// </summary>
        public BulkPriceQuantity() { }

        /// <summary>
        /// Initializes a new instance of the BulkPriceQuantity class.
        /// </summary>
        public BulkPriceQuantity(IList<PriceQuantity> requests = default(IList<PriceQuantity>))
        {
            Requests = requests;
        }

        /// <summary>
        /// This container is used by the seller to update the total
        /// 'ship-to-home' quantity of one or more inventory items (up to 25)
        /// and/or to update the price and/or quantity of one or more
        /// specific published offers.
        /// </summary>
        [JsonProperty(PropertyName = "requests")]
        public IList<PriceQuantity> Requests { get; set; }

    }
}
