// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used to identify the charitable organization associated
    /// with the listing, and the percentage of the sale proceeds that the
    /// charitable organization will receive for each sale generated by the
    /// listing. &lt;br/&gt;&lt;br/&gt;In order to receive a percentage of
    /// the sales proceeds, the charitable organization must be registered
    /// with the PayPal Giving Fund, which is a partner of eBay for Charity.
    /// </summary>
    public partial class Charity
    {
        /// <summary>
        /// Initializes a new instance of the Charity class.
        /// </summary>
        public Charity() { }

        /// <summary>
        /// Initializes a new instance of the Charity class.
        /// </summary>
        public Charity(string charityId = default(string), string donationPercentage = default(string))
        {
            CharityId = charityId;
            DonationPercentage = donationPercentage;
        }

        /// <summary>
        /// The eBay-assigned unique identifier of the charitable organization
        /// that will receive a percentage of the sales proceeds. The
        /// charitable organization must be reqistered with the PayPal Giving
        /// Fund in order to receive sales proceeds through eBay listings.
        /// This field is conditionally required if a seller is planning on
        /// donating a percentage of the sale proceeds to a charitable
        /// organization. The eBay-assigned unique identifier of a charitable
        /// organization can be found using the GetCharities call of the
        /// Trading API. In the GetCharities call response, this unique
        /// identifier is shown in the id attribute of the Charity container.
        /// </summary>
        [JsonProperty(PropertyName = "charityId")]
        public string CharityId { get; set; }

        /// <summary>
        /// This field is the percentage of the purchase price that the
        /// charitable organization (identified in the charityId field) will
        /// receive for each sale that the listing generates. This field is
        /// conditionally required if a seller is planning on donating a
        /// percentage of the sale proceeds to a charitable organization.
        /// This numeric value can range from 10 to 100, and in any 5
        /// (percent) increments in between this range (e.g. 10, 15,
        /// 20...95,... 100). The seller would pass in 10 for 10 percent, 15
        /// for 15 percent, 20 for 20 percent, and so on, all the way to 100
        /// for 100 percent.
        /// </summary>
        [JsonProperty(PropertyName = "donationPercentage")]
        public string DonationPercentage { get; set; }

    }
}
