// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the
    /// &lt;strong&gt;createOrReplaceProductCompatibility&lt;/strong&gt; call
    /// to associate compatible vehicles to an inventory item. This type is
    /// also the base response of the
    /// &lt;strong&gt;getProductCompatibility&lt;/strong&gt; call.
    /// </summary>
    public partial class Compatibility
    {
        /// <summary>
        /// Initializes a new instance of the Compatibility class.
        /// </summary>
        public Compatibility() { }

        /// <summary>
        /// Initializes a new instance of the Compatibility class.
        /// </summary>
        public Compatibility(IList<CompatibleProduct> compatibleProducts = default(IList<CompatibleProduct>), string sku = default(string))
        {
            CompatibleProducts = compatibleProducts;
            Sku = sku;
        }

        /// <summary>
        /// This container consists of an array of motor vehicles (make,
        /// model, year, trim, engine) that are compatible with the motor
        /// vehicle part or accessory specified by the sku value.
        /// </summary>
        [JsonProperty(PropertyName = "compatibleProducts")]
        public IList<CompatibleProduct> CompatibleProducts { get; set; }

        /// <summary>
        /// This is the seller-defined SKU value of the inventory item that
        /// will be associated with the compatible vehicles. This field is
        /// not applicable to the createOrReplaceProductCompatibility call,
        /// but it is always returned with the getProductCompatibility call.
        /// For the createOrReplaceProductCompatibility call, the SKU value
        /// for the inventory item is actually passed in as part of the call
        /// URI, and not in the request payload.
        /// </summary>
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

    }
}
