// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines headers for createOffer operation.
    /// </summary>
    public partial class CreateOfferHeaders
    {
        /// <summary>
        /// Initializes a new instance of the CreateOfferHeaders class.
        /// </summary>
        public CreateOfferHeaders() { }

        /// <summary>
        /// Initializes a new instance of the CreateOfferHeaders class.
        /// </summary>
        public CreateOfferHeaders(string contentLanguage = default(string))
        {
            ContentLanguage = contentLanguage;
        }

        /// <summary>
        /// This response header sets the natural language that will be
        /// provided in the field values of the response payload.
        /// </summary>
        [JsonProperty(PropertyName = "Content-Language")]
        public string ContentLanguage { get; set; }

    }
}
