// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines headers for createOrReplaceInventoryItem operation.
    /// </summary>
    public partial class CreateOrReplaceInventoryItemHeaders
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CreateOrReplaceInventoryItemHeaders class.
        /// </summary>
        public CreateOrReplaceInventoryItemHeaders() { }

        /// <summary>
        /// Initializes a new instance of the
        /// CreateOrReplaceInventoryItemHeaders class.
        /// </summary>
        public CreateOrReplaceInventoryItemHeaders(string contentLanguage = default(string))
        {
            ContentLanguage = contentLanguage;
        }

        /// <summary>
        /// This header control the language that is used for any returned
        /// errors or warnings in the call response.
        /// </summary>
        [JsonProperty(PropertyName = "Content-Language")]
        public string ContentLanguage { get; set; }

    }
}
