// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// Defines headers for createOrReplaceInventoryItemGroup operation.
    /// </summary>
    public partial class CreateOrReplaceInventoryItemGroupHeaders
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CreateOrReplaceInventoryItemGroupHeaders class.
        /// </summary>
        public CreateOrReplaceInventoryItemGroupHeaders() { }

        /// <summary>
        /// Initializes a new instance of the
        /// CreateOrReplaceInventoryItemGroupHeaders class.
        /// </summary>
        public CreateOrReplaceInventoryItemGroupHeaders(string contentLanguage = default(string))
        {
            ContentLanguage = contentLanguage;
        }

        /// <summary>
        /// This describes the natural language(s) of the intended audience
        /// for the enclosed entity
        /// </summary>
        [JsonProperty(PropertyName = "Content-Language")]
        public string ContentLanguage { get; set; }

    }
}
