// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// Defines headers for createOrReplaceProductCompatibility operation.
    /// </summary>
    public partial class CreateOrReplaceProductCompatibilityHeaders
    {
        /// <summary>
        /// Initializes a new instance of the
        /// CreateOrReplaceProductCompatibilityHeaders class.
        /// </summary>
        public CreateOrReplaceProductCompatibilityHeaders() { }

        /// <summary>
        /// Initializes a new instance of the
        /// CreateOrReplaceProductCompatibilityHeaders class.
        /// </summary>
        public CreateOrReplaceProductCompatibilityHeaders(string contentLanguage = default(string))
        {
            ContentLanguage = contentLanguage;
        }

        /// <summary>
        /// This response header sets the natural language that will be
        /// provided in the field values of the response payload.
        /// </summary>
        [JsonProperty(PropertyName = "Content-Language")]
        public string ContentLanguage { get; set; }

    }
}
