// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to specify the dimensions (and the unit used to
    /// measure those dimensions) of a shipping package. The
    /// &lt;strong&gt;dimensions&lt;/strong&gt; container is conditionally
    /// required if the seller will be offering calculated shipping rates to
    /// determine shipping cost. See the &lt;a
    /// href="https://pages.ebay.com/help/pay/calculated-shipping.html"
    /// target="_blank"&gt;Calculated shipping&lt;/a&gt; help page for more
    /// information on calculated shipping.
    /// </summary>
    public partial class Dimension
    {
        /// <summary>
        /// Initializes a new instance of the Dimension class.
        /// </summary>
        public Dimension() { }

        /// <summary>
        /// Initializes a new instance of the Dimension class.
        /// </summary>
        public Dimension(double? height = default(double?), double? length = default(double?), string unit = default(string), double? width = default(double?))
        {
            Height = height;
            Length = length;
            Unit = unit;
            Width = width;
        }

        /// <summary>
        /// The actual height (in the measurement unit specified in the unit
        /// field) of the shipping package. All fields of the dimensions
        /// container are required if package dimensions are specified. If a
        /// shipping package measured 21.5 inches in length, 15.0 inches in
        /// width, and 12.0 inches in height, the dimensions container would
        /// look as follows: &amp;quot;dimensions&amp;quot;: {
        /// &amp;quot;length&amp;quot;: 21.5,  &amp;quot;width&amp;quot;:
        /// 15.0,  &amp;quot;height&amp;quot;: 12.0,
        /// &amp;quot;unit&amp;quot;: &amp;quot;INCH&amp;quot;  }
        /// </summary>
        [JsonProperty(PropertyName = "height")]
        public double? Height { get; set; }

        /// <summary>
        /// The actual length (in the measurement unit specified in the unit
        /// field) of the shipping package. All fields of the dimensions
        /// container are required if package dimensions are specified. If a
        /// shipping package measured 21.5 inches in length, 15.0 inches in
        /// width, and 12.0 inches in height, the dimensions container would
        /// look as follows: &amp;quot;dimensions&amp;quot;: {
        /// &amp;quot;length&amp;quot;: 21.5,  &amp;quot;width&amp;quot;:
        /// 15.0,  &amp;quot;height&amp;quot;: 12.0,
        /// &amp;quot;unit&amp;quot;: &amp;quot;INCH&amp;quot;  }
        /// </summary>
        [JsonProperty(PropertyName = "length")]
        public double? Length { get; set; }

        /// <summary>
        /// The unit of measurement used to specify the dimensions of a
        /// shipping package. All fields of the dimensions container are
        /// required if package dimensions are specified. If the English
        /// system of measurement is being used, the applicable values for
        /// dimension units are FEET and INCH. If the metric system of
        /// measurement is being used, the applicable values for weight units
        /// are METER and CENTIMETER. The metric system is used by most
        /// countries outside of the US. For implementation help, refer to
        /// &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/LengthUnitOfMeasureEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "unit")]
        public string Unit { get; set; }

        /// <summary>
        /// The actual width (in the measurement unit specified in the unit
        /// field) of the shipping package. All fields of the dimensions
        /// container are required if package dimensions are specified. If a
        /// shipping package measured 21.5 inches in length, 15.0 inches in
        /// width, and 12.0 inches in height, the dimensions container would
        /// look as follows: &amp;quot;dimensions&amp;quot;: {
        /// &amp;quot;length&amp;quot;: 21.5,  &amp;quot;width&amp;quot;:
        /// 15.0,  &amp;quot;height&amp;quot;: 12.0,
        /// &amp;quot;unit&amp;quot;: &amp;quot;INCH&amp;quot;  }
        /// </summary>
        [JsonProperty(PropertyName = "width")]
        public double? Width { get; set; }

    }
}
