// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used to indicate the parameter field/value that caused an
    /// issue with the call request.
    /// </summary>
    public partial class ErrorParameter
    {
        /// <summary>
        /// Initializes a new instance of the ErrorParameter class.
        /// </summary>
        public ErrorParameter() { }

        /// <summary>
        /// Initializes a new instance of the ErrorParameter class.
        /// </summary>
        public ErrorParameter(string name = default(string), string value = default(string))
        {
            Name = name;
            Value = value;
        }

        /// <summary>
        /// This type contains the name and value of an input parameter that
        /// contributed to a specific error or warning condition.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// This is the actual value that was passed in for the element
        /// specified in the name field.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
