// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base response payload for the
    /// &lt;strong&gt;getListingFees&lt;/strong&gt; call.
    /// </summary>
    public partial class FeesSummaryResponse
    {
        /// <summary>
        /// Initializes a new instance of the FeesSummaryResponse class.
        /// </summary>
        public FeesSummaryResponse() { }

        /// <summary>
        /// Initializes a new instance of the FeesSummaryResponse class.
        /// </summary>
        public FeesSummaryResponse(IList<FeeSummary> feeSummaries = default(IList<FeeSummary>))
        {
            FeeSummaries = feeSummaries;
        }

        /// <summary>
        /// This container consists of an array of one or more listing fees
        /// that the seller can expect to pay for unpublished offers
        /// specified in the call request. Many fee types will get returned
        /// even when they are 0.0.
        /// </summary>
        [JsonProperty(PropertyName = "feeSummaries")]
        public IList<FeeSummary> FeeSummaries { get; set; }

    }
}
