// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The seller-defined Stock-Keeping Unit (SKU) of each inventory item
    /// that the user wants to retrieve is passed in the request of the
    /// &lt;strong&gt;bulkGetInventoryItem&lt;/strong&gt; method.
    /// </summary>
    public partial class GetInventoryItem
    {
        /// <summary>
        /// Initializes a new instance of the GetInventoryItem class.
        /// </summary>
        public GetInventoryItem() { }

        /// <summary>
        /// Initializes a new instance of the GetInventoryItem class.
        /// </summary>
        public GetInventoryItem(string sku = default(string))
        {
            Sku = sku;
        }

        /// <summary>
        /// An array of SKU values are passed in under the sku container to
        /// retrieve up to 25 inventory item records.
        /// </summary>
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

    }
}
