// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the response of the
    /// &lt;strong&gt;bulkGetInventoryItem&lt;/strong&gt; method to give the
    /// status of each inventory item record that the user tried to retrieve.
    /// </summary>
    public partial class GetInventoryItemResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetInventoryItemResponse class.
        /// </summary>
        public GetInventoryItemResponse() { }

        /// <summary>
        /// Initializes a new instance of the GetInventoryItemResponse class.
        /// </summary>
        public GetInventoryItemResponse(IList<Error> errors = default(IList<Error>), InventoryItemWithSkuLocaleGroupKeys inventoryItem = default(InventoryItemWithSkuLocaleGroupKeys), string sku = default(string), int? statusCode = default(int?), IList<Error> warnings = default(IList<Error>))
        {
            Errors = errors;
            InventoryItem = inventoryItem;
            Sku = sku;
            StatusCode = statusCode;
            Warnings = warnings;
        }

        /// <summary>
        /// This container will be returned if there were one or more errors
        /// associated with retrieving the inventory item record.
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<Error> Errors { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "inventoryItem")]
        public InventoryItemWithSkuLocaleGroupKeys InventoryItem { get; set; }

        /// <summary>
        /// The seller-defined Stock-Keeping Unit (SKU) of the inventory item.
        /// The seller should have a unique SKU value for every product that
        /// they sell.
        /// </summary>
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

        /// <summary>
        /// The HTTP status code returned in this field indicates the success
        /// or failure of retrieving the inventory item record for the
        /// inventory item specified in the sku field. See the HTTP status
        /// codes table to see which each status code indicates.
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// This container will be returned if there were one or more warnings
        /// associated with retrieving the inventory item record.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
