// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the base response payload of
    /// &lt;strong&gt;getInventoryItems&lt;/strong&gt; call.
    /// </summary>
    public partial class InventoryItems
    {
        /// <summary>
        /// Initializes a new instance of the InventoryItems class.
        /// </summary>
        public InventoryItems() { }

        /// <summary>
        /// Initializes a new instance of the InventoryItems class.
        /// </summary>
        public InventoryItems(string href = default(string), IList<InventoryItemWithSkuLocaleGroupid> inventoryItemsProperty = default(IList<InventoryItemWithSkuLocaleGroupid>), int? limit = default(int?), string next = default(string), string prev = default(string), int? size = default(int?), int? total = default(int?))
        {
            Href = href;
            InventoryItemsProperty = inventoryItemsProperty;
            Limit = limit;
            Next = next;
            Prev = prev;
            Size = size;
            Total = total;
        }

        /// <summary>
        /// This is the URL to the current page of inventory items.
        /// </summary>
        [JsonProperty(PropertyName = "href")]
        public string Href { get; set; }

        /// <summary>
        /// This container is an array of one or more inventory items, with
        /// detailed information on each inventory item.
        /// </summary>
        [JsonProperty(PropertyName = "inventoryItems")]
        public IList<InventoryItemWithSkuLocaleGroupid> InventoryItemsProperty { get; set; }

        /// <summary>
        /// This integer value is the number of inventory items that will be
        /// displayed on each results page.
        /// </summary>
        [JsonProperty(PropertyName = "limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// This is the URL to the next page of inventory items. This field
        /// will only be returned if there are additional inventory items to
        /// view.
        /// </summary>
        [JsonProperty(PropertyName = "next")]
        public string Next { get; set; }

        /// <summary>
        /// This is the URL to the previous page of inventory items. This
        /// field will only be returned if there are previous inventory items
        /// to view.
        /// </summary>
        [JsonProperty(PropertyName = "prev")]
        public string Prev { get; set; }

        /// <summary>
        /// This integer value indicates the total number of pages of results
        /// that are available. This number will depend on the total number
        /// of inventory items available for viewing, and on the limit value.
        /// </summary>
        [JsonProperty(PropertyName = "size")]
        public int? Size { get; set; }

        /// <summary>
        /// This integer value is the total number of inventory items that
        /// exist for the seller's account. Based on this number and on the
        /// limit value, the seller may have to toggle through multiple pages
        /// to view all inventory items.
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

    }
}
