// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used to define/modify each inventory item record that is
    /// being created and/or updated with the
    /// &lt;strong&gt;bulkCreateOrReplaceInventoryItem&lt;/strong&gt; method.
    /// Up to 25 inventory item records can be created and/or updated with
    /// one call.
    /// </summary>
    public partial class InventoryItemWithSkuLocale
    {
        /// <summary>
        /// Initializes a new instance of the InventoryItemWithSkuLocale class.
        /// </summary>
        public InventoryItemWithSkuLocale() { }

        /// <summary>
        /// Initializes a new instance of the InventoryItemWithSkuLocale class.
        /// </summary>
        public InventoryItemWithSkuLocale(Availability availability = default(Availability), string condition = default(string), string conditionDescription = default(string), string locale = default(string), PackageWeightAndSize packageWeightAndSize = default(PackageWeightAndSize), Product product = default(Product), string sku = default(string))
        {
            Availability = availability;
            Condition = condition;
            ConditionDescription = conditionDescription;
            Locale = locale;
            PackageWeightAndSize = packageWeightAndSize;
            Product = product;
            Sku = sku;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "availability")]
        public Availability Availability { get; set; }

        /// <summary>
        /// This enumeration value indicates the condition of the item.
        /// Supported item condition values will vary by eBay site and
        /// category. To see which item condition values that a particular
        /// eBay category supports, use the getItemConditionPolicies method
        /// of the Metadata API. This method returns condition ID values that
        /// map to the enumeration values defined in the ConditionEnum type.
        /// The Item condition ID and name values topic in the Selling
        /// Integration Guide has a table that maps condition ID values to
        /// ConditionEnum values. The getItemConditionPolicies call reference
        /// page has more information. A condition value is optional up until
        /// the seller is ready to publish an offer with the SKU, at which
        /// time it becomes required. Since the condition of an inventory
        /// item must be specified before being published in an offer, this
        /// field is always returned in the 'Get' calls for SKUs that are
        /// part of a published offer. If a SKU is not part of a published
        /// offer, this container will only be returned if set for the
        /// inventory item. For implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/ConditionEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "condition")]
        public string Condition { get; set; }

        /// <summary>
        /// This string field is used by the seller to more clearly describe
        /// the condition of a used inventory item, or an inventory item
        /// whose condition value is not NEW, LIKE_NEW, NEW_OTHER, or
        /// NEW_WITH_DEFECTS. The conditionDescription field is available for
        /// all eBay categories. If the conditionDescription field is used
        /// with an item in one of the new conditions (mentioned in previous
        /// paragraph), eBay will simply ignore this field if included, and
        /// eBay will return a warning message to the user. This field should
        /// only be used to further clarify the condition of the used item.
        /// It should not be used for branding, promotions, shipping,
        /// returns, payment or other information unrelated to the condition
        /// of the used item. Make sure that the condition value, condition
        /// description, listing description, and the item's pictures do not
        /// contradict one another. This field is not always required, but is
        /// required if an inventory item is being updated and a condition
        /// description already exists for that inventory item. This field is
        /// returned in the getInventoryItem, bulkGetInventoryItem, and
        /// getInventoryItems calls if a condition description was provided
        /// for a used inventory item. Max Length: 1000.
        /// </summary>
        [JsonProperty(PropertyName = "conditionDescription")]
        public string ConditionDescription { get; set; }

        /// <summary>
        /// This field is for future use only. For implementation help, refer
        /// to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/LocaleEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "packageWeightAndSize")]
        public PackageWeightAndSize PackageWeightAndSize { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "product")]
        public Product Product { get; set; }

        /// <summary>
        /// This is the seller-defined SKU value of the product that will be
        /// listed on the eBay site (specified in the marketplaceId field).
        /// Only one offer (in unpublished or published state) may exist for
        /// each sku/marketplaceId/format combination. This field is
        /// required. Max Length: 50
        /// </summary>
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

    }
}
