// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the
    /// &lt;strong&gt;createInventoryLocation&lt;/strong&gt; call to provide
    /// details on the inventory location, including the location's name,
    /// physical address, operating hours, special hours, phone number and
    /// other details of an inventory location.
    /// </summary>
    public partial class InventoryLocationFull
    {
        /// <summary>
        /// Initializes a new instance of the InventoryLocationFull class.
        /// </summary>
        public InventoryLocationFull() { }

        /// <summary>
        /// Initializes a new instance of the InventoryLocationFull class.
        /// </summary>
        public InventoryLocationFull(LocationDetails location = default(LocationDetails), string locationAdditionalInformation = default(string), string locationInstructions = default(string), IList<string> locationTypes = default(IList<string>), string locationWebUrl = default(string), string merchantLocationStatus = default(string), string name = default(string), IList<OperatingHours> operatingHours = default(IList<OperatingHours>), string phone = default(string), IList<SpecialHours> specialHours = default(IList<SpecialHours>))
        {
            Location = location;
            LocationAdditionalInformation = locationAdditionalInformation;
            LocationInstructions = locationInstructions;
            LocationTypes = locationTypes;
            LocationWebUrl = locationWebUrl;
            MerchantLocationStatus = merchantLocationStatus;
            Name = name;
            OperatingHours = operatingHours;
            Phone = phone;
            SpecialHours = specialHours;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public LocationDetails Location { get; set; }

        /// <summary>
        /// This text field is used by the merchant to provide additional
        /// information about an inventory location. Max length: 256
        /// </summary>
        [JsonProperty(PropertyName = "locationAdditionalInformation")]
        public string LocationAdditionalInformation { get; set; }

        /// <summary>
        /// This text field is generally used by the merchant to provide
        /// special pickup instructions for a store inventory location.
        /// Although this field is optional, it is recommended that merchants
        /// provide this field to create a pleasant and easy pickup
        /// experience for In-Store Pickup and Click and Collect orders. If
        /// this field is not included in the call request payload, eBay will
        /// use the default pickup instructions contained in the merchant's
        /// profile (if available).
        /// </summary>
        [JsonProperty(PropertyName = "locationInstructions")]
        public string LocationInstructions { get; set; }

        /// <summary>
        /// This container is used to define the function of the inventory
        /// location. Typically, an inventory location will serve as a store
        /// or a warehouse, but in some cases, an inventory location may be
        /// both. If this container is omitted, the location type of the
        /// inventory location will default to WAREHOUSE. See StoreTypeEnum
        /// for the supported values. Default: WAREHOUSE
        /// </summary>
        [JsonProperty(PropertyName = "locationTypes")]
        public IList<string> LocationTypes { get; set; }

        /// <summary>
        /// This text field is used by the merchant to provide the Website
        /// address (URL) associated with the inventory location. Max length:
        /// 512
        /// </summary>
        [JsonProperty(PropertyName = "locationWebUrl")]
        public string LocationWebUrl { get; set; }

        /// <summary>
        /// This field is used to indicate whether the inventory location will
        /// be enabled (inventory can be loaded to location) or disabled
        /// (inventory can not be loaded to location). If this field is
        /// omitted, a successful createInventoryLocation call will
        /// automatically enable the inventory location. A merchant may want
        /// to create a new inventory location but leave it as disabled if
        /// the inventory location is not yet ready for active inventory.
        /// Once the inventory location is ready, the merchant can use the
        /// enableInventoryLocation call to enable an inventory location that
        /// is in a disabled state. See StatusEnum for the supported values.
        /// Default: ENABLED For implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/StatusEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "merchantLocationStatus")]
        public string MerchantLocationStatus { get; set; }

        /// <summary>
        /// The name of the inventory location. This name should be a
        /// human-friendly name as it will be displayed in In-Store Pickup
        /// and Click and Collect listings. A name is not required for
        /// warehouse inventory locations. For store inventory locations,
        /// this field is not immediately required, but will be required
        /// before an offer enabled with the In-Store Pickup or Click and
        /// Collect capability can be published. So, if the seller omits this
        /// field in a createInventoryLocation call, it becomes required for
        /// an updateInventoryLocation call. Max length: 1000
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// Although not technically required, this container is highly
        /// recommended to be used to specify operating hours for a store
        /// inventory location. This container is used to express the regular
        /// operating hours for a store location during each day of the week.
        /// A dayOfWeekEnum field and an intervals container will be needed
        /// for each day of the week that the store location is open.
        /// </summary>
        [JsonProperty(PropertyName = "operatingHours")]
        public IList<OperatingHours> OperatingHours { get; set; }

        /// <summary>
        /// Although not technically required, this field is highly
        /// recommended to be used to specify the phone number for a store
        /// inventory location. Max length: 36
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

        /// <summary>
        /// This container is used to express the special operating hours for
        /// a store inventory location on a specific date, such as a holiday.
        /// The special hours specified for the specific date will override
        /// the normal operating hours for that particular day of the week.
        /// </summary>
        [JsonProperty(PropertyName = "specialHours")]
        public IList<SpecialHours> SpecialHours { get; set; }

    }
}
