// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the response of the
    /// &lt;strong&gt;bulkCreateOrReplaceInventoryItem&lt;/strong&gt; method
    /// to indicate the success or failure of creating and/or updating each
    /// inventory item record. The &lt;strong&gt;sku&lt;/strong&gt; value in
    /// this type identifies each inventory item record.
    /// </summary>
    public partial class InventoryItemResponse
    {
        /// <summary>
        /// Initializes a new instance of the InventoryItemResponse class.
        /// </summary>
        public InventoryItemResponse() { }

        /// <summary>
        /// Initializes a new instance of the InventoryItemResponse class.
        /// </summary>
        public InventoryItemResponse(IList<Error> errors = default(IList<Error>), string locale = default(string), string sku = default(string), int? statusCode = default(int?), IList<Error> warnings = default(IList<Error>))
        {
            Errors = errors;
            Locale = locale;
            Sku = sku;
            StatusCode = statusCode;
            Warnings = warnings;
        }

        /// <summary>
        /// This container will be returned if there were one or more errors
        /// associated with the creation or update to the inventory item
        /// record.
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<Error> Errors { get; set; }

        /// <summary>
        /// This field is for future use only. For implementation help, refer
        /// to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/LocaleEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "locale")]
        public string Locale { get; set; }

        /// <summary>
        /// The seller-defined Stock-Keeping Unit (SKU) of the inventory item.
        /// The seller should have a unique SKU value for every product that
        /// they sell.
        /// </summary>
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

        /// <summary>
        /// The HTTP status code returned in this field indicates the success
        /// or failure of creating or updating the inventory item record for
        /// the inventory item indicated in the sku field. See the HTTP
        /// status codes table to see which each status code indicates.
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// This container will be returned if there were one or more warnings
        /// associated with the creation or update to the inventory item
        /// record.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
