// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base response of the
    /// &lt;strong&gt;getInventoryLocation&lt;/strong&gt; and
    /// &lt;strong&gt;getInventoryLocations&lt;/strong&gt; calls. These
    /// responses provide details about inventory location(s) defined for the
    /// merchant's account.
    /// </summary>
    public partial class InventoryLocationResponse
    {
        /// <summary>
        /// Initializes a new instance of the InventoryLocationResponse class.
        /// </summary>
        public InventoryLocationResponse() { }

        /// <summary>
        /// Initializes a new instance of the InventoryLocationResponse class.
        /// </summary>
        public InventoryLocationResponse(Location location = default(Location), string locationAdditionalInformation = default(string), string locationInstructions = default(string), IList<string> locationTypes = default(IList<string>), string locationWebUrl = default(string), string merchantLocationKey = default(string), string merchantLocationStatus = default(string), string name = default(string), IList<OperatingHours> operatingHours = default(IList<OperatingHours>), string phone = default(string), IList<SpecialHours> specialHours = default(IList<SpecialHours>))
        {
            Location = location;
            LocationAdditionalInformation = locationAdditionalInformation;
            LocationInstructions = locationInstructions;
            LocationTypes = locationTypes;
            LocationWebUrl = locationWebUrl;
            MerchantLocationKey = merchantLocationKey;
            MerchantLocationStatus = merchantLocationStatus;
            Name = name;
            OperatingHours = operatingHours;
            Phone = phone;
            SpecialHours = specialHours;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "location")]
        public Location Location { get; set; }

        /// <summary>
        /// This text field provides additional information about an inventory
        /// location. This field is returned if it is set for the inventory
        /// location. Max length: 256
        /// </summary>
        [JsonProperty(PropertyName = "locationAdditionalInformation")]
        public string LocationAdditionalInformation { get; set; }

        /// <summary>
        /// This text field is used by the merchant to provide special pickup
        /// instructions for the store location. This field can help create a
        /// pleasant and easy pickup experience for In-Store Pickup and Click
        /// and Collect orders. If this field was not set up through a
        /// createInventoryLocation or a updateInventoryLocation call, eBay
        /// will use the default pickup instructions contained in the
        /// merchant's profile. Max length: 1000
        /// </summary>
        [JsonProperty(PropertyName = "locationInstructions")]
        public string LocationInstructions { get; set; }

        /// <summary>
        /// This container defines the function of the inventory location.
        /// Typically, an inventory location will serve as a store or a
        /// warehouse, but in some cases, an inventory location may be both.
        /// The location type of an inventory location defaults to WAREHOUSE
        /// if a location type is not specified when a merchant creates an
        /// inventory location.
        /// </summary>
        [JsonProperty(PropertyName = "locationTypes")]
        public IList<string> LocationTypes { get; set; }

        /// <summary>
        /// This text field shows the Website address (URL) associated with
        /// the inventory location. This field is returned if defined for the
        /// inventory location. Max length: 512
        /// </summary>
        [JsonProperty(PropertyName = "locationWebUrl")]
        public string LocationWebUrl { get; set; }

        /// <summary>
        /// The unique identifier of the inventory location. This identifier
        /// is set up by the merchant when the inventory location is first
        /// created with the createInventoryLocation call. Once this value is
        /// set for an inventory location, it cannot be modified. Max length:
        /// 36
        /// </summary>
        [JsonProperty(PropertyName = "merchantLocationKey")]
        public string MerchantLocationKey { get; set; }

        /// <summary>
        /// This field indicates whether the inventory location is enabled
        /// (inventory can be loaded to location) or disabled (inventory can
        /// not be loaded to location). The merchant can use the
        /// enableInventoryLocation call to enable an inventory location in
        /// disabled status, or the disableInventoryLocation call to disable
        /// an inventory location in enabled status. For implementation help,
        /// refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/StatusEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "merchantLocationStatus")]
        public string MerchantLocationStatus { get; set; }

        /// <summary>
        /// The name of the inventory location. This name should be a
        /// human-friendly name as it will be displayed in In-Store Pickup
        /// and Click and Collect listings. For store inventory locations,
        /// this field is not required for the createInventoryLocation call,
        /// but a store inventory location must have a defined name value
        /// before an In-Store Pickup and Click and Collect enabled offer is
        /// published. So, if the seller omits this field in the
        /// createInventoryLocation call, it will have to be added later
        /// through a updateInventoryLocation call. Max length: 1000
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// This container shows the regular operating hours for a store
        /// location during the days of the week. A dayOfWeekEnum field and
        /// an intervals container is shown for each day of the week that the
        /// store location is open.
        /// </summary>
        [JsonProperty(PropertyName = "operatingHours")]
        public IList<OperatingHours> OperatingHours { get; set; }

        /// <summary>
        /// The phone number for an inventory location. This field will
        /// typically only be set and returned for store locations. Max
        /// length: 36
        /// </summary>
        [JsonProperty(PropertyName = "phone")]
        public string Phone { get; set; }

        /// <summary>
        /// This container shows the special operating hours for a store
        /// location on a specific date or dates.
        /// </summary>
        [JsonProperty(PropertyName = "specialHours")]
        public IList<SpecialHours> SpecialHours { get; set; }

    }
}
