// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the &lt;strong&gt;inventoryItems&lt;/strong&gt;
    /// container that is returned in the response of the
    /// &lt;strong&gt;bulkMigrateListing&lt;/strong&gt; call. Up to five
    /// &lt;strong&gt;sku&lt;/strong&gt;/&lt;strong&gt;offerId&lt;/strong&gt;
    /// pairs may be returned under the
    /// &lt;strong&gt;inventoryItems&lt;/strong&gt; container, dependent on
    /// how many eBay listings the seller is attempting to migrate to the
    /// inventory model.
    /// </summary>
    public partial class InventoryItemListing
    {
        /// <summary>
        /// Initializes a new instance of the InventoryItemListing class.
        /// </summary>
        public InventoryItemListing() { }

        /// <summary>
        /// Initializes a new instance of the InventoryItemListing class.
        /// </summary>
        public InventoryItemListing(string offerId = default(string), string sku = default(string))
        {
            OfferId = offerId;
            Sku = sku;
        }

        /// <summary>
        /// Upon a successful migration of a listing, eBay auto-generates this
        /// unique identifier, and this offer ID value will be used to
        /// retrieve and manage the newly-created offer object. This value
        /// will only be generated and returned if the eBay listing is
        /// migrated successfully.
        /// </summary>
        [JsonProperty(PropertyName = "offerId")]
        public string OfferId { get; set; }

        /// <summary>
        /// This is the seller-defined SKU value associated with the item(s)
        /// in a listing. This same SKU value will be used to retrieve and
        /// manage the newly-created inventory item object if the listing
        /// migration is successful. This SKU value will get returned even if
        /// the migration is not successful.
        /// </summary>
        [JsonProperty(PropertyName = "sku")]
        public string Sku { get; set; }

    }
}
