// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the &lt;b&gt;createInventoryLocation&lt;/b&gt;
    /// call to provide an full or partial address of an inventory location.
    /// </summary>
    public partial class LocationDetails
    {
        /// <summary>
        /// Initializes a new instance of the LocationDetails class.
        /// </summary>
        public LocationDetails() { }

        /// <summary>
        /// Initializes a new instance of the LocationDetails class.
        /// </summary>
        public LocationDetails(Address address = default(Address), GeoCoordinates geoCoordinates = default(GeoCoordinates))
        {
            Address = address;
            GeoCoordinates = geoCoordinates;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public Address Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "geoCoordinates")]
        public GeoCoordinates GeoCoordinates { get; set; }

    }
}
