// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// A complex type that is used to provide the physical address of a
    /// location, and it geo-coordinates.
    /// </summary>
    public partial class Location
    {
        /// <summary>
        /// Initializes a new instance of the Location class.
        /// </summary>
        public Location() { }

        /// <summary>
        /// Initializes a new instance of the Location class.
        /// </summary>
        public Location(Address address = default(Address), GeoCoordinates geoCoordinates = default(GeoCoordinates), string locationId = default(string))
        {
            Address = address;
            GeoCoordinates = geoCoordinates;
            LocationId = locationId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public Address Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "geoCoordinates")]
        public GeoCoordinates GeoCoordinates { get; set; }

        /// <summary>
        /// A unique eBay-assigned ID for the location. Note: This field
        /// should not be confused with the seller-defined
        /// merchantLocationKey value. It is the merchantLocationKey value
        /// which is used to identify an inventory location when working with
        /// inventory location API calls. The locationId value is only used
        /// internally by eBay.
        /// </summary>
        [JsonProperty(PropertyName = "locationId")]
        public string LocationId { get; set; }

    }
}
