// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base response payload for the
    /// &lt;strong&gt;getInventoryLocations&lt;/strong&gt; call.
    /// </summary>
    public partial class LocationResponse
    {
        /// <summary>
        /// Initializes a new instance of the LocationResponse class.
        /// </summary>
        public LocationResponse() { }

        /// <summary>
        /// Initializes a new instance of the LocationResponse class.
        /// </summary>
        public LocationResponse(string href = default(string), int? limit = default(int?), string next = default(string), int? offset = default(int?), string prev = default(string), int? total = default(int?), IList<InventoryLocationResponse> locations = default(IList<InventoryLocationResponse>))
        {
            Href = href;
            Limit = limit;
            Next = next;
            Offset = offset;
            Prev = prev;
            Total = total;
            Locations = locations;
        }

        /// <summary>
        /// The URI of the current page of results from the result set.
        /// </summary>
        [JsonProperty(PropertyName = "href")]
        public string Href { get; set; }

        /// <summary>
        /// The number of items returned on a single page from the result set.
        /// </summary>
        [JsonProperty(PropertyName = "limit")]
        public int? Limit { get; set; }

        /// <summary>
        /// The URI for the following page of results. This value is returned
        /// only if there is an additional page of results to display from
        /// the result set. Max length: 2048
        /// </summary>
        [JsonProperty(PropertyName = "next")]
        public string Next { get; set; }

        /// <summary>
        /// The number of results skipped in the result set before listing the
        /// first returned result. This value is set in the request with the
        /// offset query parameter. Note: The items in a paginated result set
        /// use a zero-based list where the first item in the list has an
        /// offset of 0.
        /// </summary>
        [JsonProperty(PropertyName = "offset")]
        public int? Offset { get; set; }

        /// <summary>
        /// The URI for the preceding page of results. This value is returned
        /// only if there is a previous page of results to display from the
        /// result set. Max length: 2048
        /// </summary>
        [JsonProperty(PropertyName = "prev")]
        public string Prev { get; set; }

        /// <summary>
        /// The total number of items retrieved in the result set. If no items
        /// are found, this field is returned with a value of 0.
        /// </summary>
        [JsonProperty(PropertyName = "total")]
        public int? Total { get; set; }

        /// <summary>
        /// An array of one or more of the merchant's inventory locations.
        /// </summary>
        [JsonProperty(PropertyName = "locations")]
        public IList<InventoryLocationResponse> Locations { get; set; }

    }
}
