// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to display the results of each listing that the
    /// seller attempted to migrate.
    /// </summary>
    public partial class MigrateListingResponse
    {
        /// <summary>
        /// Initializes a new instance of the MigrateListingResponse class.
        /// </summary>
        public MigrateListingResponse() { }

        /// <summary>
        /// Initializes a new instance of the MigrateListingResponse class.
        /// </summary>
        public MigrateListingResponse(IList<Error> errors = default(IList<Error>), string inventoryItemGroupKey = default(string), IList<InventoryItemListing> inventoryItems = default(IList<InventoryItemListing>), string listingId = default(string), string marketplaceId = default(string), int? statusCode = default(int?), IList<Error> warnings = default(IList<Error>))
        {
            Errors = errors;
            InventoryItemGroupKey = inventoryItemGroupKey;
            InventoryItems = inventoryItems;
            ListingId = listingId;
            MarketplaceId = marketplaceId;
            StatusCode = statusCode;
            Warnings = warnings;
        }

        /// <summary>
        /// If one or more errors occur with the attempt to migrate the
        /// listing, this container will be returned with detailed
        /// information on each error.
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<Error> Errors { get; set; }

        /// <summary>
        /// This field will only be returned for a multiple-variation listing
        /// that the seller attempted to migrate. Its value is auto-generated
        /// by eBay. For a multiple-variation listing that is successfully
        /// migrated to the new Inventory model, eBay automatically creates
        /// an inventory item group object for the listing, and the seller
        /// will be able to retrieve and manage that new inventory item group
        /// object by using the value in this field.
        /// </summary>
        [JsonProperty(PropertyName = "inventoryItemGroupKey")]
        public string InventoryItemGroupKey { get; set; }

        /// <summary>
        /// This container exists of an array of SKU values and offer IDs. For
        /// single-variation listings, this will only be one SKU value and
        /// one offer ID (if listing was successfully migrated), but multiple
        /// SKU values and offer IDs will be returned for multiple-variation
        /// listings.
        /// </summary>
        [JsonProperty(PropertyName = "inventoryItems")]
        public IList<InventoryItemListing> InventoryItems { get; set; }

        /// <summary>
        /// The unique identifier of the eBay listing that the seller
        /// attempted to migrate.
        /// </summary>
        [JsonProperty(PropertyName = "listingId")]
        public string ListingId { get; set; }

        /// <summary>
        /// This is the unique identifier of the eBay Marketplace where the
        /// listing resides. The value fo the eBay US site will be EBAY_US.
        /// For implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/MarketplaceEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "marketplaceId")]
        public string MarketplaceId { get; set; }

        /// <summary>
        /// This field is returned for each listing that the seller attempted
        /// to migrate. See the HTTP status codes table to see which each
        /// status code indicates.
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// If one or more warnings occur with the attempt to migrate the
        /// listing, this container will be returned with detailed
        /// information on each warning. It is possible that a listing can be
        /// successfully migrated even if a warning occurs.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
