// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to specify one to five eBay listings that will be
    /// migrated to the new Inventory model.
    /// </summary>
    public partial class MigrateListing
    {
        /// <summary>
        /// Initializes a new instance of the MigrateListing class.
        /// </summary>
        public MigrateListing() { }

        /// <summary>
        /// Initializes a new instance of the MigrateListing class.
        /// </summary>
        public MigrateListing(string listingId = default(string))
        {
            ListingId = listingId;
        }

        /// <summary>
        /// The unique identifier of the eBay listing to migrate to the new
        /// Inventory model. In the Trading API, this field is known as the
        /// ItemID. Up to five unique eBay listings may be specified here in
        /// separate listingId fields. The seller should make sure that each
        /// of these listings meet the requirements that are stated at the
        /// top of this Call Reference page.
        /// </summary>
        [JsonProperty(PropertyName = "listingId")]
        public string ListingId { get; set; }

    }
}
