// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the
    /// &lt;strong&gt;compatibilityProperties&lt;/strong&gt; container to
    /// identify a motor vehicle using name/value pairs.
    /// </summary>
    public partial class NameValueList
    {
        /// <summary>
        /// Initializes a new instance of the NameValueList class.
        /// </summary>
        public NameValueList() { }

        /// <summary>
        /// Initializes a new instance of the NameValueList class.
        /// </summary>
        public NameValueList(string name = default(string), string value = default(string))
        {
            Name = name;
            Value = value;
        }

        /// <summary>
        /// This string value identifies the motor vehicle aspect, such as
        /// 'make', 'model', 'year', 'trim', and 'engine'. Typically, the
        /// make, model, and year of the motor vehicle are always required,
        /// with the trim and engine being necessary sometimes, but it will
        /// be dependent on the part or accessory, and on the vehicle class.
        /// </summary>
        [JsonProperty(PropertyName = "name")]
        public string Name { get; set; }

        /// <summary>
        /// This string value identifies the motor vehicle aspect specified in
        /// the corresponding name field. For example, if the name field is
        /// 'make', this field may be 'Toyota', or if the name field is
        /// 'model', this field may be 'Camry'.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
