// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used to indicate the status of each offer that the user
    /// attempted to publish. If an offer is successfully published, an eBay
    /// listing ID (also known as an Item ID) is returned. If there is an
    /// issue publishing the offer and creating the new eBay listing, the
    /// information about why the listing failed should be returned in the
    /// &lt;strong&gt;errors&lt;/strong&gt; and/or
    /// &lt;strong&gt;warnings&lt;/strong&gt; containers.
    /// </summary>
    public partial class OfferResponseWithListingId
    {
        /// <summary>
        /// Initializes a new instance of the OfferResponseWithListingId class.
        /// </summary>
        public OfferResponseWithListingId() { }

        /// <summary>
        /// Initializes a new instance of the OfferResponseWithListingId class.
        /// </summary>
        public OfferResponseWithListingId(IList<Error> errors = default(IList<Error>), string listingId = default(string), string offerId = default(string), int? statusCode = default(int?), IList<Error> warnings = default(IList<Error>))
        {
            Errors = errors;
            ListingId = listingId;
            OfferId = offerId;
            StatusCode = statusCode;
            Warnings = warnings;
        }

        /// <summary>
        /// This container will be returned if there were one or more errors
        /// associated with publishing the offer.
        /// </summary>
        [JsonProperty(PropertyName = "errors")]
        public IList<Error> Errors { get; set; }

        /// <summary>
        /// The unique identifier of the newly-created eBay listing. This
        /// field is only returned if the seller successfully published the
        /// offer and created the new eBay listing.
        /// </summary>
        [JsonProperty(PropertyName = "listingId")]
        public string ListingId { get; set; }

        /// <summary>
        /// The unique identifier of the offer that the seller published (or
        /// attempted to publish).
        /// </summary>
        [JsonProperty(PropertyName = "offerId")]
        public string OfferId { get; set; }

        /// <summary>
        /// The HTTP status code returned in this field indicates the success
        /// or failure of publishing the offer specified in the offerId
        /// field. See the HTTP status codes table to see which each status
        /// code indicates.
        /// </summary>
        [JsonProperty(PropertyName = "statusCode")]
        public int? StatusCode { get; set; }

        /// <summary>
        /// This container will be returned if there were one or more warnings
        /// associated with publishing the offer.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
