// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the response payload of the
    /// &lt;strong&gt;createOffer&lt;/strong&gt; and
    /// &lt;strong&gt;updateOffer&lt;/strong&gt; calls, and contains the
    /// unique identifier for the offer if the offer is successfully
    /// created/updated, as well as any errors and/or warnings that may have
    /// been triggered by the call.
    /// </summary>
    public partial class OfferResponse
    {
        /// <summary>
        /// Initializes a new instance of the OfferResponse class.
        /// </summary>
        public OfferResponse() { }

        /// <summary>
        /// Initializes a new instance of the OfferResponse class.
        /// </summary>
        public OfferResponse(string offerId = default(string), IList<Error> warnings = default(IList<Error>))
        {
            OfferId = offerId;
            Warnings = warnings;
        }

        /// <summary>
        /// The unique identifier of the offer that was just created with a
        /// createOffer call, or just updated with an updateOffer call. It is
        /// not returned if the createOffer call fails to create an offer.
        /// This identifier will be needed for many offer-related calls.
        /// </summary>
        [JsonProperty(PropertyName = "offerId")]
        public string OfferId { get; set; }

        /// <summary>
        /// This container will contain an array of errors and/or warnings
        /// when a call is made, and errors and/or warnings occur.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
