// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base request payload of the
    /// &lt;strong&gt;getListingFees&lt;/strong&gt; call.
    /// </summary>
    public partial class OfferKeysWithId
    {
        /// <summary>
        /// Initializes a new instance of the OfferKeysWithId class.
        /// </summary>
        public OfferKeysWithId() { }

        /// <summary>
        /// Initializes a new instance of the OfferKeysWithId class.
        /// </summary>
        public OfferKeysWithId(IList<OfferKeyWithId> offers = default(IList<OfferKeyWithId>))
        {
            Offers = offers;
        }

        /// <summary>
        /// This container is used to identify one or more (up to
        /// 250)unpublished offers for which expected listing fees will be
        /// retrieved. The user passes one or more offerId values (maximum of
        /// 250) in to this container to identify the unpublished offers in
        /// which to retrieve expected listing fees. This call is only
        /// applicable for offers in the unpublished state. The call response
        /// gives aggregate fee amounts per eBay marketplace, and does not
        /// give fee information at the individual offer level.
        /// </summary>
        [JsonProperty(PropertyName = "offers")]
        public IList<OfferKeyWithId> Offers { get; set; }

    }
}
