// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to express the regular operating hours of a
    /// merchant's store during the days of the week.
    /// </summary>
    public partial class OperatingHours
    {
        /// <summary>
        /// Initializes a new instance of the OperatingHours class.
        /// </summary>
        public OperatingHours() { }

        /// <summary>
        /// Initializes a new instance of the OperatingHours class.
        /// </summary>
        public OperatingHours(string dayOfWeekEnum = default(string), IList<Interval> intervals = default(IList<Interval>))
        {
            DayOfWeekEnum = dayOfWeekEnum;
            Intervals = intervals;
        }

        /// <summary>
        /// A dayOfWeekEnum value is required for each day of the week that
        /// the store location has regular operating hours. This field is
        /// returned if operating hours are defined for the store location.
        /// For implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/DayOfWeekEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "dayOfWeekEnum")]
        public string DayOfWeekEnum { get; set; }

        /// <summary>
        /// This container is used to define the opening and closing times of
        /// a store's working day (defined in the dayOfWeekEnum field). An
        /// intervals container is needed for each day of the week that the
        /// store location is open. If a store location closes for lunch (or
        /// any other period during the day) and then reopens, multiple open
        /// and close pairs are needed This container is returned if
        /// operating hours are defined for the store location.
        /// </summary>
        [JsonProperty(PropertyName = "intervals")]
        public IList<Interval> Intervals { get; set; }

    }
}
