// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to indicate the package type, weight, and dimensions
    /// of the shipping package. Package weight and dimensions are required
    /// when calculated shipping rates are used, and weight alone is required
    /// when flat-rate shipping is used, but with a weight surcharge. See the
    /// &lt;a href="https://pages.ebay.com/help/pay/calculated-shipping.html"
    /// target="_blank"&gt;Calculated shipping&lt;/a&gt; help page for more
    /// information on calculated shipping.
    /// </summary>
    public partial class PackageWeightAndSize
    {
        /// <summary>
        /// Initializes a new instance of the PackageWeightAndSize class.
        /// </summary>
        public PackageWeightAndSize() { }

        /// <summary>
        /// Initializes a new instance of the PackageWeightAndSize class.
        /// </summary>
        public PackageWeightAndSize(Dimension dimensions = default(Dimension), string packageType = default(string), Weight weight = default(Weight))
        {
            Dimensions = dimensions;
            PackageType = packageType;
            Weight = weight;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "dimensions")]
        public Dimension Dimensions { get; set; }

        /// <summary>
        /// This enumeration value indicates the type of shipping package used
        /// to ship the inventory item. The supported values for this field
        /// can be found in the PackageTypeEnum type. This field will be
        /// returned if the package type is set for the inventory item. For
        /// implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/PackageTypeEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "packageType")]
        public string PackageType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "weight")]
        public Weight Weight { get; set; }

    }
}
