// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to specify/indicate the quantity of the inventory
    /// item that is available for an In-Store Pickup order at the merchant's
    /// physical store (specified by the
    /// &lt;strong&gt;merchantLocationKey&lt;/strong&gt; field).
    /// </summary>
    public partial class PickupAtLocationAvailability
    {
        /// <summary>
        /// Initializes a new instance of the PickupAtLocationAvailability
        /// class.
        /// </summary>
        public PickupAtLocationAvailability() { }

        /// <summary>
        /// Initializes a new instance of the PickupAtLocationAvailability
        /// class.
        /// </summary>
        public PickupAtLocationAvailability(string availabilityType = default(string), TimeDuration fulfillmentTime = default(TimeDuration), string merchantLocationKey = default(string), int? quantity = default(int?))
        {
            AvailabilityType = availabilityType;
            FulfillmentTime = fulfillmentTime;
            MerchantLocationKey = merchantLocationKey;
            Quantity = quantity;
        }

        /// <summary>
        /// The enumeration value in this field indicates the availability
        /// status of the inventory item at the merchant's physical store
        /// specified by the pickupAtLocationAvailability.merchantLocationKey
        /// field. This field is required if the pickupAtLocationAvailability
        /// container is used, and is always returned with the
        /// pickupAtLocationAvailability container. See AvailabilityTypeEnum
        /// for more information about how/when you use each enumeration
        /// value. For implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/AvailabilityTypeEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "availabilityType")]
        public string AvailabilityType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "fulfillmentTime")]
        public TimeDuration FulfillmentTime { get; set; }

        /// <summary>
        /// The unique identifier of a merchant's store where the In-Store
        /// Pickup inventory item is currently located, or where inventory
        /// will be sent to. If the merchant's store is currently awaiting
        /// for inventory, the availabilityType value should be
        /// SHIP_TO_STORE. This field is required if the
        /// pickupAtLocationAvailability container is used, and is always
        /// returned with the pickupAtLocationAvailability container. Max
        /// length: 36
        /// </summary>
        [JsonProperty(PropertyName = "merchantLocationKey")]
        public string MerchantLocationKey { get; set; }

        /// <summary>
        /// This integer value indicates the quantity of the inventory item
        /// that is available for In-Store Pickup at the store identified by
        /// the merchantLocationKey value. The value of quantity should be an
        /// integer value greater than 0, unless the inventory item is out of
        /// stock. This field is required if the pickupAtLocationAvailability
        /// container is used, and is always returned with the
        /// pickupAtLocationAvailability container.
        /// </summary>
        [JsonProperty(PropertyName = "quantity")]
        public int? Quantity { get; set; }

    }
}
