// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used to specify the listing price for the product and
    /// settings for the Minimum Advertised Price and Strikethrough Pricing
    /// features. The &lt;strong&gt;price&lt;/strong&gt; field must be
    /// supplied before an offer is published, but a seller may create an
    /// offer without supplying a price initially. The Minimum Advertised
    /// Price feature is only available on the US site. Strikethrough Pricing
    /// is available on the US, eBay Motors, UK, Germany, Canada (English and
    /// French), France, Italy, and Spain sites.
    /// </summary>
    public partial class PricingSummary
    {
        /// <summary>
        /// Initializes a new instance of the PricingSummary class.
        /// </summary>
        public PricingSummary() { }

        /// <summary>
        /// Initializes a new instance of the PricingSummary class.
        /// </summary>
        public PricingSummary(Amount minimumAdvertisedPrice = default(Amount), string originallySoldForRetailPriceOn = default(string), Amount originalRetailPrice = default(Amount), Amount price = default(Amount), string pricingVisibility = default(string))
        {
            MinimumAdvertisedPrice = minimumAdvertisedPrice;
            OriginallySoldForRetailPriceOn = originallySoldForRetailPriceOn;
            OriginalRetailPrice = originalRetailPrice;
            Price = price;
            PricingVisibility = pricingVisibility;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "minimumAdvertisedPrice")]
        public Amount MinimumAdvertisedPrice { get; set; }

        /// <summary>
        /// This field is needed if the Strikethrough Pricing (STP) feature
        /// will be used in the offer. This field indicates that the product
        /// was sold for the price in the originalRetailPrice field on an
        /// eBay site, or sold for that price by a third-party retailer. When
        /// using the createOffer or updateOffer calls, the seller will pass
        /// in a value of ON_EBAY to indicate that the product was sold for
        /// the originalRetailPrice on an eBay site, or the seller will pass
        /// in a value of OFF_EBAY to indicate that the product was sold for
        /// the originalRetailPrice through a third-party retailer. This
        /// field and the originalRetailPrice field are only applicable if
        /// the seller and listing are eligible to use the Strikethrough
        /// Pricing feature, a feature which is limited to the US (core site
        /// and Motors), UK, Germany, Canada (English and French versions),
        /// France, Italy, and Spain sites. This field will be returned if
        /// set for the offer. For implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/SoldOnEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "originallySoldForRetailPriceOn")]
        public string OriginallySoldForRetailPriceOn { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "originalRetailPrice")]
        public Amount OriginalRetailPrice { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "price")]
        public Amount Price { get; set; }

        /// <summary>
        /// This field is needed if the Minimum Advertised Price (MAP) feature
        /// will be used in the offer. This field is only applicable if an
        /// eligible US seller is using the Minimum Advertised Price (MAP)
        /// feature and a minimumAdvertisedPrice has been specified. The
        /// value set in this field will determine whether the MAP price is
        /// shown to a prospective buyer prior to checkout through a pop-up
        /// window accessed from the View Item page, or if the MAP price is
        /// not shown until the checkout flow after the buyer has already
        /// committed to buying the item. To show the MAP price prior to
        /// checkout, the seller will set this value to PRE_CHECKOUT. To show
        /// the MAP price after the buyer already commits to buy the item,
        /// the seller will set this value to DURING_CHECKOUT. This field
        /// will be ignored if the seller and/or the listing is not eligible
        /// for the MAP feature. This field will be returned if set for the
        /// offer. For implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/MinimumAdvertisedPriceHandlingEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "pricingVisibility")]
        public string PricingVisibility { get; set; }

    }
}
