// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base response payload of the
    /// &lt;strong&gt;publishOffer&lt;/strong&gt; and
    /// &lt;strong&gt;publishOfferByInventoryItemGroup&lt;/strong&gt; calls.
    /// </summary>
    public partial class PublishResponse
    {
        /// <summary>
        /// Initializes a new instance of the PublishResponse class.
        /// </summary>
        public PublishResponse() { }

        /// <summary>
        /// Initializes a new instance of the PublishResponse class.
        /// </summary>
        public PublishResponse(string listingId = default(string), IList<Error> warnings = default(IList<Error>))
        {
            ListingId = listingId;
            Warnings = warnings;
        }

        /// <summary>
        /// The unique identifier of the newly created eBay listing. This
        /// field is returned if the single offer (if publishOffer call was
        /// used) or group of offers in an inventory item group (if
        /// publishOfferByInventoryItemGroup call was used) was successfully
        /// converted into an eBay listing.
        /// </summary>
        [JsonProperty(PropertyName = "listingId")]
        public string ListingId { get; set; }

        /// <summary>
        /// This container will contain an array of errors and/or warnings if
        /// any occur when a publishOffer or publishOfferByInventoryItemGroup
        /// call is made.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
