// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used if the seller wants to override the shipping costs
    /// or surcharge associated with a specific domestic or international
    /// shipping service option defined in the fulfillment listing policy
    /// that is being applied toward the offer. The shipping-related costs
    /// that can be overridden include the shipping cost to ship one item,
    /// the shipping cost to ship each additional item (if multiple quantity
    /// are purchased), and the shipping surcharge applied to the shipping
    /// service option.
    /// </summary>
    public partial class ShippingCostOverride
    {
        /// <summary>
        /// Initializes a new instance of the ShippingCostOverride class.
        /// </summary>
        public ShippingCostOverride() { }

        /// <summary>
        /// Initializes a new instance of the ShippingCostOverride class.
        /// </summary>
        public ShippingCostOverride(Amount additionalShippingCost = default(Amount), int? priority = default(int?), Amount shippingCost = default(Amount), string shippingServiceType = default(string), Amount surcharge = default(Amount))
        {
            AdditionalShippingCost = additionalShippingCost;
            Priority = priority;
            ShippingCost = shippingCost;
            ShippingServiceType = shippingServiceType;
            Surcharge = surcharge;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "additionalShippingCost")]
        public Amount AdditionalShippingCost { get; set; }

        /// <summary>
        /// The integer value input into this field, along with the
        /// shippingServiceType value, sets which domestic or international
        /// shipping service option in the fulfillment policy will be
        /// modified with updated shipping costs. Specifically, the
        /// shippingCostOverrides.shippingServiceType value in a createOffer
        /// or updateOffer call must match the shippingOptions.optionType
        /// value in a fulfillment listing policy, and the
        /// shippingCostOverrides.priority value in a createOffer or
        /// updateOffer call must match the
        /// shippingOptions.shippingServices.sortOrderId value in a
        /// fulfillment listing policy. This field is always required when
        /// overriding the shipping costs of a shipping service option, and
        /// will be always be returned for each shipping service option whose
        /// costs are being overridden.
        /// </summary>
        [JsonProperty(PropertyName = "priority")]
        public int? Priority { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "shippingCost")]
        public Amount ShippingCost { get; set; }

        /// <summary>
        /// This enumerated value indicates whether the shipping service
        /// specified in the priority field is a domestic or an international
        /// shipping service option. To override the shipping costs for a
        /// specific domestic shipping service in the fulfillment listing
        /// policy, this field should be set to DOMESTIC, and to override the
        /// shipping costs for each international shipping service, this
        /// field should be set to INTERNATIONAL. This value, along with
        /// priority value, sets which domestic or international shipping
        /// service option in the fulfillment policy that will be modified
        /// with updated shipping costs. Specifically, the
        /// shippingCostOverrides.shippingServiceType value in a createOffer
        /// or updateOffer call must match the shippingOptions.optionType
        /// value in a fulfillment listing policy, and the
        /// shippingCostOverrides.priority value in a createOffer or
        /// updateOffer call must match the
        /// shippingOptions.shippingServices.sortOrderId value in a
        /// fulfillment listing policy. This field is always required when
        /// overriding the shipping costs of a shipping service option, and
        /// will be always be returned for each shipping service option whose
        /// costs are being overridden. For implementation help, refer to
        /// &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/ShippingServiceTypeEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "shippingServiceType")]
        public string ShippingServiceType { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "surcharge")]
        public Amount Surcharge { get; set; }

    }
}
