// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used to show the version number and instance of the
    /// service or API.
    /// </summary>
    public partial class Version
    {
        /// <summary>
        /// Initializes a new instance of the Version class.
        /// </summary>
        public Version() { }

        /// <summary>
        /// Initializes a new instance of the Version class.
        /// </summary>
        public Version(Version instance = default(Version), string versionProperty = default(string))
        {
            Instance = instance;
            VersionProperty = versionProperty;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "instance")]
        public Version Instance { get; set; }

        /// <summary>
        /// The version number of the service or API.
        /// </summary>
        [JsonProperty(PropertyName = "version")]
        public string VersionProperty { get; set; }

    }
}
