// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// The base response of the &lt;strong&gt;withdrawOffer&lt;/strong&gt;
    /// call.
    /// </summary>
    public partial class WithdrawResponse
    {
        /// <summary>
        /// Initializes a new instance of the WithdrawResponse class.
        /// </summary>
        public WithdrawResponse() { }

        /// <summary>
        /// Initializes a new instance of the WithdrawResponse class.
        /// </summary>
        public WithdrawResponse(string listingId = default(string), IList<Error> warnings = default(IList<Error>))
        {
            ListingId = listingId;
            Warnings = warnings;
        }

        /// <summary>
        /// The unique identifier of the eBay listing associated with the
        /// offer that was withdrawn. This field will not be returned if the
        /// eBay listing was not successfully ended.
        /// </summary>
        [JsonProperty(PropertyName = "listingId")]
        public string ListingId { get; set; }

        /// <summary>
        /// This container will be returned if there were one or more warnings
        /// associated with the attempt to withdraw the offer.
        /// </summary>
        [JsonProperty(PropertyName = "warnings")]
        public IList<Error> Warnings { get; set; }

    }
}
