// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebayinventory.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type is used by the base request of the
    /// &lt;strong&gt;WithdrawByInventoryItemGroup&lt;/strong&gt; method,
    /// which is used to end a multiple-variation listing.
    /// </summary>
    public partial class WithdrawByInventoryItemGroupRequest
    {
        /// <summary>
        /// Initializes a new instance of the
        /// WithdrawByInventoryItemGroupRequest class.
        /// </summary>
        public WithdrawByInventoryItemGroupRequest() { }

        /// <summary>
        /// Initializes a new instance of the
        /// WithdrawByInventoryItemGroupRequest class.
        /// </summary>
        public WithdrawByInventoryItemGroupRequest(string inventoryItemGroupKey = default(string), string marketplaceId = default(string))
        {
            InventoryItemGroupKey = inventoryItemGroupKey;
            MarketplaceId = marketplaceId;
        }

        /// <summary>
        /// This is the unique identifier of the inventory item group. This
        /// identifier is automatically generated by eBay once an inventory
        /// item group is created. This field is required.
        /// </summary>
        [JsonProperty(PropertyName = "inventoryItemGroupKey")]
        public string InventoryItemGroupKey { get; set; }

        /// <summary>
        /// This is the unique identifier of the eBay site for which the offer
        /// will be made available. The marketPlaceId enumeration values are
        /// found in MarketplaceIdEnum. This field is required. For
        /// implementation help, refer to &lt;a
        /// href='https://developer.ebay.com/devzone/rest/api-ref/inventory/types/MarketplaceEnum.html'&gt;eBay
        /// API documentation&lt;/a&gt;
        /// </summary>
        [JsonProperty(PropertyName = "marketplaceId")]
        public string MarketplaceId { get; set; }

    }
}
