// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type contains information about one of the ancestors of a
    /// suggested category. An ordered list of these references describes the
    /// path from the suggested category to the root of the category tree it
    /// belongs to.
    /// </summary>
    public partial class AncestorReference
    {
        /// <summary>
        /// Initializes a new instance of the AncestorReference class.
        /// </summary>
        public AncestorReference() { }

        /// <summary>
        /// Initializes a new instance of the AncestorReference class.
        /// </summary>
        public AncestorReference(string categoryId = default(string), string categoryName = default(string), string categorySubtreeNodeHref = default(string), int? categoryTreeNodeLevel = default(int?))
        {
            CategoryId = categoryId;
            CategoryName = categoryName;
            CategorySubtreeNodeHref = categorySubtreeNodeHref;
            CategoryTreeNodeLevel = categoryTreeNodeLevel;
        }

        /// <summary>
        /// The unique identifier of the eBay ancestor category. Note: The
        /// root node of a full default category tree includes the categoryId
        /// field, but its value should not be relied upon. It provides no
        /// useful information for application development.
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public string CategoryId { get; set; }

        /// <summary>
        /// The name of the ancestor category identified by categoryId.
        /// </summary>
        [JsonProperty(PropertyName = "categoryName")]
        public string CategoryName { get; set; }

        /// <summary>
        /// The href portion of the getCategorySubtree call that retrieves the
        /// subtree below the ancestor category node.
        /// </summary>
        [JsonProperty(PropertyName = "categorySubtreeNodeHref")]
        public string CategorySubtreeNodeHref { get; set; }

        /// <summary>
        /// The absolute level of the ancestor category node in the hierarchy
        /// of its category tree. Note: The root node of any full category
        /// tree is always at level 0.
        /// </summary>
        [JsonProperty(PropertyName = "categoryTreeNodeLevel")]
        public int? CategoryTreeNodeLevel { get; set; }

    }
}
