// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type contains a valid value for an aspect, along with any
    /// constraints on the occurrence of that value.
    /// </summary>
    public partial class AspectValue
    {
        /// <summary>
        /// Initializes a new instance of the AspectValue class.
        /// </summary>
        public AspectValue() { }

        /// <summary>
        /// Initializes a new instance of the AspectValue class.
        /// </summary>
        public AspectValue(string localizedValue = default(string), IList<ValueConstraint> valueConstraints = default(IList<ValueConstraint>))
        {
            LocalizedValue = localizedValue;
            ValueConstraints = valueConstraints;
        }

        /// <summary>
        /// The localized value of this aspect. Note: This value is always
        /// localized for the specified marketplace.
        /// </summary>
        [JsonProperty(PropertyName = "localizedValue")]
        public string LocalizedValue { get; set; }

        /// <summary>
        /// Not returned if the value of the localizedValue field can always
        /// be selected for this aspect of the specified category. Contains a
        /// list of the dependencies that identify when the value of the
        /// localizedValue field is available for the current aspect. Each
        /// dependency specifies the values of another aspect of the same
        /// category (a control aspect), for which the current value of the
        /// current aspect can also be selected by the seller. Example: A
        /// shirt is available in three sizes and three colors, but only the
        /// Small and Medium sizes come in Green. Thus for the Color aspect,
        /// the value Green is constrained by its dependency on Size (the
        /// control aspect). Only when the Size aspect value is Small or
        /// Medium, can the Color aspect value of Green be selected by the
        /// seller.
        /// </summary>
        [JsonProperty(PropertyName = "valueConstraints")]
        public IList<ValueConstraint> ValueConstraints { get; set; }

    }
}
