// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type contains information about an item attribute (for example,
    /// color) that is appropriate or necessary for accurately describing
    /// items in a particular leaf category. Sellers are required or
    /// encouraged to provide one or more values of this aspect when offering
    /// an item in that category on eBay.
    /// </summary>
    public partial class Aspect
    {
        /// <summary>
        /// Initializes a new instance of the Aspect class.
        /// </summary>
        public Aspect() { }

        /// <summary>
        /// Initializes a new instance of the Aspect class.
        /// </summary>
        public Aspect(AspectConstraint aspectConstraint = default(AspectConstraint), IList<AspectValue> aspectValues = default(IList<AspectValue>), string localizedAspectName = default(string))
        {
            AspectConstraint = aspectConstraint;
            AspectValues = aspectValues;
            LocalizedAspectName = localizedAspectName;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "aspectConstraint")]
        public AspectConstraint AspectConstraint { get; set; }

        /// <summary>
        /// Contains a list of valid values for this aspect (for example: Red,
        /// Green, and Blue), along with any constraints on those values.
        /// </summary>
        [JsonProperty(PropertyName = "aspectValues")]
        public IList<AspectValue> AspectValues { get; set; }

        /// <summary>
        /// The localized name of this aspect (for example: Colour on the eBay
        /// UK site). Note: This name is always localized for the specified
        /// marketplace.
        /// </summary>
        [JsonProperty(PropertyName = "localizedAspectName")]
        public string LocalizedAspectName { get; set; }

    }
}
