// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type contains information about a particular eBay category.
    /// </summary>
    public partial class Category
    {
        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        public Category() { }

        /// <summary>
        /// Initializes a new instance of the Category class.
        /// </summary>
        public Category(string categoryId = default(string), string categoryName = default(string))
        {
            CategoryId = categoryId;
            CategoryName = categoryName;
        }

        /// <summary>
        /// The unique identifier of the eBay category within its category
        /// tree. Note: The root node of a full default category tree
        /// includes the categoryId field, but its value should not be relied
        /// upon. It provides no useful information for application
        /// development.
        /// </summary>
        [JsonProperty(PropertyName = "categoryId")]
        public string CategoryId { get; set; }

        /// <summary>
        /// The name of the category identified by categoryId.
        /// </summary>
        [JsonProperty(PropertyName = "categoryName")]
        public string CategoryName { get; set; }

    }
}
