// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    /// <summary>
    /// This type contains information about a particular subtree of a
    /// specified eBay category tree. A category subtree consists of a
    /// non-root node of the category tree, and all of its descendants down
    /// to the leaf nodes.
    /// </summary>
    public partial class CategorySubtree
    {
        /// <summary>
        /// Initializes a new instance of the CategorySubtree class.
        /// </summary>
        public CategorySubtree() { }

        /// <summary>
        /// Initializes a new instance of the CategorySubtree class.
        /// </summary>
        public CategorySubtree(CategoryTreeNode categorySubtreeNode = default(CategoryTreeNode), string categoryTreeId = default(string), string categoryTreeVersion = default(string))
        {
            CategorySubtreeNode = categorySubtreeNode;
            CategoryTreeId = categoryTreeId;
            CategoryTreeVersion = categoryTreeVersion;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "categorySubtreeNode")]
        public CategoryTreeNode CategorySubtreeNode { get; set; }

        /// <summary>
        /// The unique identifier of the eBay category tree to which this
        /// subtree belongs.
        /// </summary>
        [JsonProperty(PropertyName = "categoryTreeId")]
        public string CategoryTreeId { get; set; }

        /// <summary>
        /// The version of the category tree identified by categoryTreeId.
        /// It's a good idea to cache this value for comparison so you can
        /// determine if this category tree has been modified in subsequent
        /// calls.
        /// </summary>
        [JsonProperty(PropertyName = "categoryTreeVersion")]
        public string CategoryTreeVersion { get; set; }

    }
}
