// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the
    /// &lt;strong&gt;compatibilityPropertyValues&lt;/strong&gt; array that
    /// is returned in the
    /// &lt;strong&gt;getCompatibilityPropertyValues&lt;/strong&gt; response.
    /// The &lt;strong&gt;compatibilityPropertyValues&lt;/strong&gt; array
    /// contains all compatible vehicle property values that match the
    /// specified eBay marketplace, specified eBay category, and filters in
    /// the request. If the
    /// &lt;strong&gt;compatibility_property&lt;/strong&gt; parameter value
    /// in the request is 'Trim', each value returned in each
    /// &lt;strong&gt;value&lt;/strong&gt; field will be a different vehicle
    /// trim, applicable to any filters that are set in the
    /// &lt;string&gt;filter&lt;/string&gt; query parameter of the request,
    /// and also based on the eBay marketplace and category specified in the
    /// call request.
    /// </summary>
    public partial class CompatibilityPropertyValue
    {
        /// <summary>
        /// Initializes a new instance of the CompatibilityPropertyValue class.
        /// </summary>
        public CompatibilityPropertyValue() { }

        /// <summary>
        /// Initializes a new instance of the CompatibilityPropertyValue class.
        /// </summary>
        public CompatibilityPropertyValue(string value = default(string))
        {
            Value = value;
        }

        /// <summary>
        /// Each value field shows one applicable compatible vehicle property
        /// value. The values that are returned will depend on the specified
        /// eBay marketplace, specified eBay category, and filters in the
        /// request.
        /// </summary>
        [JsonProperty(PropertyName = "value")]
        public string Value { get; set; }

    }
}
