// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type is used by the base response of the
    /// &lt;strong&gt;getCompatibilityProperties&lt;/strong&gt; method.
    /// </summary>
    public partial class GetCompatibilityMetadataResponse
    {
        /// <summary>
        /// Initializes a new instance of the GetCompatibilityMetadataResponse
        /// class.
        /// </summary>
        public GetCompatibilityMetadataResponse() { }

        /// <summary>
        /// Initializes a new instance of the GetCompatibilityMetadataResponse
        /// class.
        /// </summary>
        public GetCompatibilityMetadataResponse(IList<CompatibilityProperty> compatibilityProperties = default(IList<CompatibilityProperty>))
        {
            CompatibilityProperties = compatibilityProperties;
        }

        /// <summary>
        /// This container consists of an array of all compatible vehicle
        /// properties applicable to the specified eBay marketplace and eBay
        /// category ID.
        /// </summary>
        [JsonProperty(PropertyName = "compatibilityProperties")]
        public IList<CompatibilityProperty> CompatibilityProperties { get; set; }

    }
}
