// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace ebaytaxonomy.Models
{
    using System.Collections.Generic;
    using Newtonsoft.Json;

    /// <summary>
    /// This type contains a list of the dependencies that identify when a
    /// particular value is available for a given aspect of a given category.
    /// Each dependency specifies the values of another aspect of the same
    /// category (the &lt;i&gt;control&lt;/i&gt; aspect), for which the given
    /// value of the given aspect can also be selected by the seller. This
    /// container consists of constraint information for the corresponding
    /// product aspect value.
    /// </summary>
    public partial class ValueConstraint
    {
        /// <summary>
        /// Initializes a new instance of the ValueConstraint class.
        /// </summary>
        public ValueConstraint() { }

        /// <summary>
        /// Initializes a new instance of the ValueConstraint class.
        /// </summary>
        public ValueConstraint(string applicableForLocalizedAspectName = default(string), IList<string> applicableForLocalizedAspectValues = default(IList<string>))
        {
            ApplicableForLocalizedAspectName = applicableForLocalizedAspectName;
            ApplicableForLocalizedAspectValues = applicableForLocalizedAspectValues;
        }

        /// <summary>
        /// The name of the control aspect on which the current aspect value
        /// depends.
        /// </summary>
        [JsonProperty(PropertyName = "applicableForLocalizedAspectName")]
        public string ApplicableForLocalizedAspectName { get; set; }

        /// <summary>
        /// Contains a list of the values of the control aspect on which this
        /// aspect's value depends. When the control aspect has any of the
        /// specified values, the current value of the current aspect will
        /// also be available.
        /// </summary>
        [JsonProperty(PropertyName = "applicableForLocalizedAspectValues")]
        public IList<string> ApplicableForLocalizedAspectValues { get; set; }

    }
}
