# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    - name: Restore nuget packages
      run: |
        cd ui-agent
        dotnet restore

    - name: Install electronize tool
      run: |
        dotnet tool install ElectronNET.CLI -g

    - name: Build client apps
      run: |
        dotnet build
        electronize build /target windows
