# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
    branches: [ master ]

jobs:
  clients:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.5.0
      with:
        dotnet-version: 3.1.x

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
      with:
        node-version: 12.x

    - name: Restore packages and build
      run: |
        dotnet restore
        dotnet build

    - name: Install electronize tool
      run: |
        dotnet tool install ElectronNET.CLI -g

    - name: Build client app packages
      run: |
        cd ui-agent
        electronize build /target win
        electronize build /target linux
        # electronize build /target osx
  server:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v2
    - name: Docker Image
      uses: docker/build-push-action@v1
      with:
        tags: latest
        dockerfile: bifrost/Dockerfile
